### Demonstrate method for converting CCAP landcover classes to COAWST classes  
This is the first part of a two-step process.
1) Convert CCAP to one a handful of COAWST classes
2) Populate the initial arrays with data related to the COAWST class (e.g., stem density, etc).

An alternative would be to define the veg characteristics for each class.

In [1]:
import numpy as np

In [2]:
# lookup table for converting C-CAP landcover to a simplified classification

# COAWST landcover classes: we can expand this list if we need to.
CClass = { 0 : "NoData",
           1 : "bare",
           2 : "grassy",
           3 : "woody",
          }

# CCAP landcover classes
# Tuple contains name and corresponding COAWST class. Those classes could be reassigned.
# Classes we would not expect (e.g., tundra) return 0 as a warning something might be amiss
CCAP = { 0: ( "Background" , 0 ),
         1: ( "Unclassified", 0 ),
         2: ( "Developed, High Intensity", 1 ),
         3: ( "Developed, Medium Intensity", 1 ),
         4: ( "Devleoped, Low Intensity", 1 ),
         5: ( "Developed, Open Space", 1 ),
         6: ( "Cultivated Crops", 2 ),
         7: ( "Pasture/Hay", 2 ),
         8: ( "Grassland/Herbaceous", 2),
         9: ( "Deciduous Forest", 3 ),
        10: ( "Evergreen Forest", 3 ),
        11: ( "Mixed Forest", 3 ),
        12: ( "Scrub/Shrub", 3 ),
        13: ( "Palustrine Forested Wetland", 3 ),
        14: ( "Palustrine Scrub/Shrub Wetland", 3 ),
        15: ( "Palustrine Emergent Wetland (Peristent)", 2 ),
        16: ( "Estuarine Forested Wetland", 3 ),
        17: ( "Estuarine Scrub/Shrub Wetland", 3, ),
        18: ( "Estuarine Emergent Wetland", 2 ),
        19: ( "Unconsolidated Shore", 1 ),
        20: ( "Barren Land", 1 ),
        21: ( "Open Water", 1 ),
        22: ( "Palustrine Aquatic Bed", 1 ),
        23: ( "Estuarine Aquatic Bed", 1 ),
        24: ( "Tundra", 0 ), 
        25: ( "Perennial Ice/Snow", 0 ),        
       }

In [3]:
print("CCAP COAWST")
for key in CCAP:
    print(CCAP[key][0],'->', CClass[CCAP[key][1]])

CCAP COAWST
Background -> NoData
Unclassified -> NoData
Developed, High Intensity -> bare
Developed, Medium Intensity -> bare
Devleoped, Low Intensity -> bare
Developed, Open Space -> bare
Cultivated Crops -> grassy
Pasture/Hay -> grassy
Grassland/Herbaceous -> grassy
Deciduous Forest -> woody
Evergreen Forest -> woody
Mixed Forest -> woody
Scrub/Shrub -> woody
Palustrine Forested Wetland -> woody
Palustrine Scrub/Shrub Wetland -> woody
Palustrine Emergent Wetland (Peristent) -> grassy
Estuarine Forested Wetland -> woody
Estuarine Scrub/Shrub Wetland -> woody
Estuarine Emergent Wetland -> grassy
Unconsolidated Shore -> bare
Barren Land -> bare
Open Water -> bare
Palustrine Aquatic Bed -> bare
Estuarine Aquatic Bed -> bare
Tundra -> NoData
Perennial Ice/Snow -> NoData


In [4]:
# Make a fake array of CCAP classes
a = np.reshape( np.random.randint( 0, 25+1, size = 30 ), (5,6) )
print(a)

[[21 21 11 18  5 12]
 [23 25  2 18  4 22]
 [ 2 14 24  8  3 20]
 [ 4  1 19 19 20  8]
 [13  6 24 10  6  0]]


In [5]:
# Convert to COAWST classes
# brute force
s = np.shape(a)
print("Shape: ",s)
b = np.zeros_like( a )
for j in range (s[1]):
    for i in range (s[0]):
        b[i,j] = CCAP[a[i,j]][1]

Shape:  (5, 6)


In [6]:
print(b)

[[1 1 3 2 1 3]
 [1 0 1 2 1 1]
 [1 3 0 2 1 1]
 [1 0 1 1 1 2]
 [3 2 0 3 2 0]]
