### Demonstrate method for converting CCAP landcover classes to COAWST classes  
This is the first part of a two-step process.
1) Convert CCAP to one a handful of COAWST classes
2) Populate the initial arrays with data related to the COAWST class (e.g., stem density, etc).

An alternative would be to define the veg characteristics for each class.

In [1]:
import numpy as np

In [2]:
# lookup table for converting C-CAP landcover to a simplified classification

# COAWST landcover classes: we can expand this list if we need to.

#CCLass: indices to tuples
iDescription = 0
iPlantHeight_m = 1
iPlantThick_m = 2
iStemDens_stems_m2 = 3
iStemDiam_m = 4

#   Id: (Name, PlantHeight(m), PlantThick(m), StemDens(stems/m2), StemDiam(m) )   
CClass = {
    0: ("NoData"    ,        0,   0,      0,   0 ), 
    1: ("open water",        0,   0,      0,   0), 
    2: ("sandy"     ,        0,   0,      0,   0),       
    3: ("grassy veg",        0.5, 0.005,  1.0, 0.03),
    4: ("woody veg" ,        2.0, 0.005, 10.0, 0.03),
    5: ("marshy veg",        0.5, 0.005,  1.0, 0.03),
    6: ("devel open",        0,   0,      0,   0),    
    7: ("devel structures", 10,   1,      1,   1)
    }

# CCAP landcover classes
# Tuple contains name and corresponding COAWST class. Those classes could be reassigned.
# Classes we would not expect (e.g., tundra) return 0 as a warning something might be amiss
CCAP = { 0: ( "Background" , 0 ),
         1: ( "Unclassified", 0 ),
         2: ( "Developed, High Intensity", 7 ),
         3: ( "Developed, Medium Intensity", 7 ),
         4: ( "Devleoped, Low Intensity", 7 ),
         5: ( "Developed, Open Space", 6 ),
         6: ( "Cultivated Crops", 3 ),
         7: ( "Pasture/Hay", 3 ),
         8: ( "Grassland/Herbaceous", 3),
         9: ( "Deciduous Forest", 4 ),
        10: ( "Evergreen Forest", 4 ),
        11: ( "Mixed Forest", 4 ),
        12: ( "Scrub/Shrub", 4 ),
        13: ( "Palustrine Forested Wetland", 5 ),
        14: ( "Palustrine Scrub/Shrub Wetland", 5 ),
        15: ( "Palustrine Emergent Wetland (Peristent)", 5 ),
        16: ( "Estuarine Forested Wetland", 4 ),
        17: ( "Estuarine Scrub/Shrub Wetland", 4, ),
        18: ( "Estuarine Emergent Wetland", 5 ),
        19: ( "Unconsolidated Shore", 2 ),
        20: ( "Barren Land", 2 ),
        21: ( "Open Water", 1 ),
        22: ( "Palustrine Aquatic Bed", 1 ),
        23: ( "Estuarine Aquatic Bed", 1 ),
        24: ( "Tundra", 0 ), 
        25: ( "Perennial Ice/Snow", 0 ),        
       }



In [3]:
print("CCAP -> COAWST")
for key in CCAP:
    print(CCAP[key][0],'->', CClass[CCAP[key][1]])

CCAP -> COAWST
Background -> ('NoData', 0, 0, 0, 0)
Unclassified -> ('NoData', 0, 0, 0, 0)
Developed, High Intensity -> ('devel structures', 10, 1, 1, 1)
Developed, Medium Intensity -> ('devel structures', 10, 1, 1, 1)
Devleoped, Low Intensity -> ('devel structures', 10, 1, 1, 1)
Developed, Open Space -> ('devel open', 0, 0, 0, 0)
Cultivated Crops -> ('grassy veg', 0.5, 0.005, 1.0, 0.03)
Pasture/Hay -> ('grassy veg', 0.5, 0.005, 1.0, 0.03)
Grassland/Herbaceous -> ('grassy veg', 0.5, 0.005, 1.0, 0.03)
Deciduous Forest -> ('woody veg', 2.0, 0.005, 10.0, 0.03)
Evergreen Forest -> ('woody veg', 2.0, 0.005, 10.0, 0.03)
Mixed Forest -> ('woody veg', 2.0, 0.005, 10.0, 0.03)
Scrub/Shrub -> ('woody veg', 2.0, 0.005, 10.0, 0.03)
Palustrine Forested Wetland -> ('marshy veg', 0.5, 0.005, 1.0, 0.03)
Palustrine Scrub/Shrub Wetland -> ('marshy veg', 0.5, 0.005, 1.0, 0.03)
Palustrine Emergent Wetland (Peristent) -> ('marshy veg', 0.5, 0.005, 1.0, 0.03)
Estuarine Forested Wetland -> ('woody veg', 2.0, 

In [4]:
# Make a fake array of CCAP classes
a = np.reshape( np.random.randint( 0, 25+1, size = 30 ), (5,6) )
print(a)

[[ 6 17  5 16  2 18]
 [ 9 17 23 16 10 24]
 [15 19  4 14 23  6]
 [14 12 10 23 11 12]
 [11  8  5  4 11  4]]


In [5]:
CClass[CCAP[8][1]][iPlantHeight_m]

0.5

In [6]:
# Convert array of CCAP classes to array of values for, e.g., plant height
# brute force - there might be a faster way to do this
s = np.shape(a)
print("Shape: ",s)
b = np.nan*np.zeros_like( a )
for j in range (s[1]):
    for i in range (s[0]):
        b[i,j] = CClass[CCAP[a[i,j]][1]][iPlantHeight_m]
        
print(b)

Shape:  (5, 6)
[[ 0.5  2.   0.   2.  10.   0.5]
 [ 2.   2.   0.   2.   2.   0. ]
 [ 0.5  0.  10.   0.5  0.   0.5]
 [ 0.5  2.   2.   0.   2.   2. ]
 [ 2.   0.5  0.  10.   2.  10. ]]
