In [40]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 100, num=101)
y = np.linspace(0,150, num=151)
X, Y = np.meshgrid(x,y)
Z = np.zeros_like(X)
XYZ = np.vstack((X.ravel(),Y.ravel(),Z.ravel())).T
print(XYZ)

[[  0.   0.   0.]
 [  1.   0.   0.]
 [  2.   0.   0.]
 ...
 [ 98. 150.   0.]
 [ 99. 150.   0.]
 [100. 150.   0.]]


In [41]:
# coordinates for two cameras
c1 = np.array((0,0,0))
c2 = np.array((5,10,0))

In [55]:
A = np.sqrt( np.sum( (XYZ-c1)**2, 0 ) )
B = np.sqrt( np.sum( (XYZ-c2)**2, 1 ) )
print(np.shape(XYZ))
print(np.shape((XYZ-c1)**2))
print(np.shape(A))

(15251, 3)
(15251, 3)
(3,)


In [43]:
C = np.sqrt( np.sum((c2-c1)**2) )
print(C)

11.180339887498949


In [44]:
print(np.shape(A))

()


In [36]:
def SSS(A, B, C):
    arg = (A * A + B * B - C * C)/(2.0 * A * B)
    print(arg)
    return np.degrees(np.arccos( arg ) )

ang = SSS(A, B, C)
print(ang)

1.004479493507984
nan


/tmp/ipykernel_338321/2238658704.py:4: RuntimeWarning: invalid value encountered in arccos
  return np.degrees(np.arccos( arg ) )
